services:
  - type: web
    name: conversion-craft-worker
    runtime: python
    repo: https://github.com/Anwarito-lbd/conversion.craft-
    region: oregon
    rootDir: apps/worker
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
